os: linux
language: node_js
dist: xenial

jobs:
  include:
    - language: android
      jdk: openjdk8
      env:
        - NODE_VERSION=14.14.0
        - ANDROID_API=29
        - ANDROID_BUILD_TOOLS=29.0.2
        - IS_TRAVIS=true
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.cache/yarn/
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      android:
        components:
          - tools
          - platform-tools
          - android-${ANDROID_API}
          - build-tools-${ANDROID_BUILD_TOOLS}

      before_install:
        - yes | sdkmanager "ndk-bundle" > /dev/null
        - yes | sdkmanager "ndk;21.2.6472646" > /dev/null
        - yes | sdkmanager "cmake;3.10.2.4988404" > /dev/null

      install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - node --version
        - npm install -g yarn --ignore-dependencies
        - npm install -g react-native-cli
        - yarn
        - cd Example
        - yarn

      before_script:
        - export ANDROID_NDK=$ANDROID_HOME/ndk-bundle
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        - export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT

      script:
        - cd ./android &&./gradlew assembleDebug --console=plain

    - language: objective-c
      os: osx
      xcode_workspace: './ios/ReanimatedExample.xcworkspace'
      xcode_scheme: ReanimatedExample
      xcode_sdk: iphonesimulator12.4
      osx_image: xcode12.2
      podfile: './ios/Podfile'
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
      env: NODE_VERSION=14.14.0

      branches:
        only:
          - master

      cache: yarn

      install:
        - nvm --version
        - echo $NODE_VERSION
        - xcodebuild -version
        - sudo launchctl limit maxfiles 2048 unlimited
        - sudo ulimit -n 10000
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - brew install yarn --ignore-dependencies
        - npm install -g react-native-cli
        - cd Example
        - yarn
        - gem install cocoapods
        - cd ios && pod install && cd ..

      script:
        - xcodebuild -workspace ./ios/ReanimatedExample.xcworkspace -scheme ReanimatedExample -configuration Debug -sdk iphonesimulator -derivedDataPath ./ios/build -quiet | xcpretty

    - language: node_js
      node_js:
        - 14
      cache:
        directories:
          - node_modules
      script:
        - yarn
        - yarn run type:check
        - yarn test
